### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Hirooso** [EvilBytecode/WindKitty-Protector#1]
Dear Evilbytecode,

I consider myself aa person with very limited knowledge in computer science. In recent days, I've encountered some security issues online, I believe hackers attempted to compromise my Instagram profile and successfully breached my Vinted account(where i had my credit card), even managing to reset the password via SMS and calling me at 4 AM.

Lately, I've noticed that when I turn on my computer, the cmd window briefly opens and then closes automatically. This situation has raised some concerns regarding the security of my system.
I've been advised to seek information about the security of the "cybershield/protection" script you have published on GitHub, and I thought I'd kindly ask you for some insights. I'm sorry for any language issues but English is not my primary language so i'm using a translator.
I would like to ensure that the script is reliable and safe to use. If you could, I would greatly appreciate it if you could share more details about the security of the script. Additionally, could you kindly explain how I should use and run it? Your guidance on these matters would be incredibly helpful. Additionally, given my recent experiences, could you kindly offer any advice on how to protect my accounts, especially in light of the recent incidents with hackers resetting passwords through SMS?

thank you in advance for your time

Best regards.

**Comment by EvilBytecode** [comment]
Hello, I am considering releasing a compiled version, which will be in the form of an `.exe` file. If you have concerns about trusting `.exe` files, especially considering what happened to your computer, you can easily decompile it using tools like ILSpy or DNSpy. If you prefer to run the open-source version, please follow these steps:

1. Download this repository as a zip file.
2. Extract 'cybsershield' into your 'Downloads' folder (ensure it is not in a zip file, but only a folder).
3. Open Command Prompt (`cmd`) and navigate to the folder using the `cd` command followed by the path to the folder with the PowerShell file.
4. Execute the following command: `Powershell -File .\Protector.ps1` after navigating to the correct folder.

If you need help contact me ❤️

**Comment by Hirooso** [comment]
Hello EvilBytecode 
I was installing the script but it gave me some errors could you help me?
```


Unregister-ScheduledTask : Nessun oggetto MSFT_ScheduledTask trovato con la proprietà 'TaskName'
uguale a 'KDOT'. Verificare il valore della proprietà e riprovare.
In C:\Users\*****\Downloads\WindKitty-Protector-main\Protector.ps1:109 car:5
+     Unregister-ScheduledTask -TaskName "KDOT" -Confirm:$False
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (KDOT:String) [Unregister-ScheduledTask], CimJobExcepti
   on
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound_TaskName,Unregister-ScheduledTask

Remove-Item : Impossibile trovare il percorso 'C:\Users\******\AppData\Roaming\KDOT' perché non
esiste.
In C:\Users\*****\Downloads\WindKitty-Protector-main\Protector.ps1:110 car:5
+     Remove-Item -Path "$env:appdata\KDOT" -force -recurse
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\****\AppData\Roaming\KDOT:String) [Remove-I
   tem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

[~] Successfully Uninstalled !
[+] Found sum y should remove it if its executable:  C:\Users\*****\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup :
C:\Users\****\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\desktop.ini
[+] Found sum y should remove it if its executable:  C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup :
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\desktop.ini
[+] No Malicious Files Have been found in startups.
[+] Discord wasn't infected.


[NOMORECOOKIES] This Protects you from Rats And Grabbers..
[+] Protects from Known Rats Like: AsyncRAT, Quasar RAT, Venom Rat, XWorm RAT, DC Rat etc..
[+] And also from known grabbers such as: Redline Stealer, Blank Stealer, Umbral Stealer etc..


Do you want to install NoMoreCookies? http://github.com/AdvDebug/NoMoreCookies/releases/download/NoMoreCookies_2.3/NoMoreCookies-2.3.zip ? (y/n): y
NMR Saved to: C:\Users\****\Downloads\NoMoreCookies.zip****


```
Best Regards.

**Comment by EvilBytecode** [comment]
hello this is completly normal for the kdot, it checked if you have any task in your task schedluer.. and youre good, desktop ini ignore its completly normal, but download nmr and run and choose option 1 or 2

**Comment by Hirooso** [comment]
And for uninstalling the script. Could you kindly confirm if it is sufficient to remove the entire folder in which the script is contained, or if there are additional steps involved?

Thank you for your assistance.

Best regards.

**Comment by EvilBytecode** [comment]
no no, all is automated, it installs a NMC (NO MORE COOKIES) and its stored in uhh downloads folder, the script automatically launches it. but the 1 /2  option isnt automated

**Comment by Hirooso** [comment]
Could you please provide guidance on how to UNinstall the script properly? Specifically, does deleting the entire folder in which the script is located suffice, or are there additional steps required?

Best regards,

**Comment by EvilBytecode** [comment]
just delete the folder, thats all.
